"""LLM 抽象（OpenAI 兼容，§5.5.5）：译标题 / 抽属性 / 通用对话。"""
from typing import Protocol

class LLMProvider(Protocol):
    name: str
    async def chat(self, messages: list[dict], **opts) -> str: ...
    async def translate(self, text: str, target_lang: str = "zh") -> str: ...
    async def extract_json(self, prompt: str) -> dict: ...
